TrajectoryPlannerROS:
  max_vel_x: 0.45
  min_vel_x: 0.0
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.4

  max_rot_vel: 5.0  # choose slightly less than the base's capability
  min_rot_vel: 0.4  # this is the min angular velocity when there is negligible translational velocity
  rot_stopped_vel: 0.4

  acc_lim_x: 1.0
  acc_lim_theta: 2.0
  acc_lim_y: 2.0      # diff drive robot

  holonomic_robot: true