obstacle_range: 2.5
raytrace_range: 3.0
footprint: [ [0.265, -0.24], [0.265, 0.24], [-0.265, 0.24], [-0.265, -0.24] ]
inflation_radius: 0.3

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: base_link, data_type: LaserScan, topic: scan_filtered, marking: true, clearing: true}