global_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  publish_frequency: 1.0

  transform_tolerance: 0.2

  static_map    : false
  rolling_window: true
  width         : 16.0
  height        : 16.0
  resolution    :  0.05

  track_unknown_space: true
  unknown_cost_value : 255

  plugins:
  - name: obstacle_laser_layer
    type: 'costmap_2d::ObstacleLayer'

  obstacle_laser_layer:
    enabled: true
    observation_sources: laser_scan_sensor
    combination_method: 0

    laser_scan_sensor:
      sensor_frame: base_scan
      data_type: LaserScan
      topic: /scan_filtered
      expected_update_rate: 0.3
      observation_persistence: 1.0
      inf_is_valid: true
      marking: true
      clearing: true
      raytrace_range: 5.5
      obstacle_range: 5.0
      min_obstacle_height: -0.1
      max_obstacle_height: 0.3
  
  inflation_layer:
    enabled            : true
    inflation_radius   : 1.0
    cost_scaling_factor: 2.0