controller_list:
  - name: /xarm/xarm6_traj_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: /DASHGO/gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - Rev1Servo
