# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.3
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  Cam1Rev1:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  Cam1Rev2:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  Rev1Servo:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  Rev2Servo:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  joint1:
    default_velocity_scaling_factor: 0.3
    default_acceleration_scaling_factor: 0.065
    has_velocity_limits: true
    max_velocity: 0.8
    has_acceleration_limits: false
    max_acceleration: 0
  joint2:
    default_velocity_scaling_factor: 0.3
    default_acceleration_scaling_factor: 0.065
    has_velocity_limits: true
    max_velocity: 0.8
    has_acceleration_limits: false
    max_acceleration: 0
  joint3:
    default_velocity_scaling_factor: 0.3
    default_acceleration_scaling_factor: 0.065
    has_velocity_limits: true
    max_velocity: 0.8
    has_acceleration_limits: false
    max_acceleration: 0
  joint4:
    default_velocity_scaling_factor: 0.3
    default_acceleration_scaling_factor: 0.065
    has_velocity_limits: true
    max_velocity: 0.8
    has_acceleration_limits: false
    max_acceleration: 0
  joint5:
    default_velocity_scaling_factor: 0.3
    default_acceleration_scaling_factor: 0.065
    has_velocity_limits: true
    max_velocity: 0.8
    has_acceleration_limits: false
    max_acceleration: 0
  odom_r:
    has_velocity_limits: true
    max_velocity: 0.18
    has_acceleration_limits: false
    max_acceleration: 0
  odom_x:
    has_velocity_limits: true
    max_velocity: 0.08
    has_acceleration_limits: false
    max_acceleration: 0
  odom_y:
    has_velocity_limits: true
    max_velocity: 0.08
    has_acceleration_limits: false
    max_acceleration: 0