# Example configuration:
# - velocity limits are around a 10% above the physical limits
# - acceleration limits are just low enough to avoid jerking

# Mandatory parameters
speed_lim_v_x: 0.4
speed_lim_v_y: 0.0
speed_lim_w: 1.0

accel_lim_v_x: 0.2
accel_lim_v_y: 0.0
accel_lim_w: 0.35

# Optional parameters
frequency: 20.0
decel_factor: 20.0

# Robot velocity feedback type:
#  0 - none
#  1 - odometry
#  2 - end robot commands
robot_feedback: 0

