controller_frequency: 3.0  # Sets the frequency of the controller. (Default: 3.0)
recovery_behavior_enabled: true  # Enables recovery behavior when the trajectory planner fails. (Default: true)
clearing_rotation_allowed: true  # Allows rotation for obstacle clearing. (Default: true)

TrajectoryPlannerROS:  # Configuration for the TrajectoryPlannerROS module.
   max_vel_x: 0.25  # Maximum linear velocity in the x-axis. (Default: 0.5)
   min_vel_x: 0.05  # Minimum linear velocity in the x-axis. (Default: 0.1)
   max_vel_y: 0.0  # Maximum linear velocity in the y-axis (zero for a differential drive robot). (Default: 0.0)
   min_vel_y: 0.0  # Minimum linear velocity in the y-axis. (Default: 0.0)
   min_in_place_vel_theta: 0.5  # Minimum velocity for in-place rotation. (Default: 0.4)
   escape_vel: -0.1  # Velocity used for escaping from a failed trajectory. (Default: -0.1)
   acc_lim_x: 0.5  # Maximum linear acceleration in the x-axis. (Default: 2.5)
   acc_lim_y: 0.0  # Maximum linear acceleration in the y-axis (zero for a differential drive robot). (Default: 2.5)
   acc_lim_theta: 0.5  # Maximum angular acceleration. (Default: 3.2)

   holonomic_robot: false  # Indicates whether the robot is holonomic (able to move freely) or not. (Default: false)
   yaw_goal_tolerance: 0.1  # Tolerance for reaching the goal orientation (in radians). (Default: 0.05)
   xy_goal_tolerance: 0.1  # Tolerance for reaching the goal position in the x and y axes (in meters). (Default: 0.1)
   latch_xy_goal_tolerance: false  # Determines whether to maintain the xy_goal_tolerance after reaching it. (Default: false)
   pdist_scale: 0.4  # Scaling factor for the path distance cost. (Default: 0.6)
   gdist_scale: 0.8  # Scaling factor for the goal distance cost. (Default: 0.8)
   meter_scoring: true  # Determines whether to use meters as the unit for scoring. (Default: false)

   heading_lookahead: 0.325  # Distance to look ahead for heading scoring. (Default: 0.325)
   heading_scoring: true  # Enables heading scoring. (Default: false)
   heading_scoring_timestep: 0.8  # Time step for heading scoring. (Default: 0.8)
   occdist_scale: 0.05  # Scaling factor for the obstacle distance cost. (Default: 0.01)
   oscillation_reset_dist: 0.05  # Distance threshold for resetting oscillation flags. (Default: 0.05)
   publish_cost_grid_pc: false  # Determines whether to publish cost grid as point cloud. (Default: false)
   prune_plan: true  # Enables plan pruning. (Default: true)

   sim_time: 1.0  # Simulation time for trajectory generation. (Default: 1.0)
   sim_granularity: 0.025  # Granularity for linear simulation. (Default: 0.025)
   angular_sim_granularity: 0.025  # Granularity for angular simulation. (Default: 0.025)
   vx_samples: 8  # Number of linear velocity samples. (Default: 3)
   vy_samples: 0  # Number of linear velocity samples in the y-axis (zero for a differential drive robot). (Default: 0)
   vtheta_samples: 20  # Number of angular velocity samples. (Default: 20)
   dwa: true  # Enables the Dynamic Window Approach. (Default: true)
   simple_attractor: false  # Determines whether to use a simple attractor or not. (Default: false)
