footprint: [[-0.085, -0.20], [-0.085, 0.2],[0.315, 0.2], [0.315, -0.2]]

obstacle_layer:
  enabled: true
  max_obstacle_height: 1.6
  min_obstacle_height: 0.0
  obstacle_range: 2.0
  raytrace_range: 2.0
  inflation_radius: 0.10
  combination_method: 1
  observation_sources: laser_scan_sensor  camera_depth
  track_unknown_space: true
 
  origin_z: 0.0
  z_resolution: 0.1
  z_voxels: 10
  unknown_threshold: 15
  mark_threshold: 0
  publish_voxel_map: true
  footprint_clearing_enabled: true

  laser_scan_sensor_2:
    data_type: LaserScan
    topic: /scan_2
    marking: true
    clearing: true
    expected_update_rate: 0
    min_obstacle_height: 0.01
    max_obstacle_height: 0.1

  sonar_scan_sensor:
    data_type: PointCloud2
    topic: /sonar_cloudpoint
    marking: true
    clearing: true
    min_obstacle_height: 0.11
    max_obstacle_height: 0.2
    observation_persistence: 0.0

  laser_scan_sensor:
    data_type: LaserScan
    topic: /scan
    marking: true
    clearing: true
    expected_update_rate: 0
    min_obstacle_height: 0.21
    max_obstacle_height: 0.30


  other_sensor_data:
    data_type: PointCloud
    topic: /other_sensor_data 
    marking: true
    clearing: true
    min_obstacle_height: 0.31
    max_obstacle_height: 0.4

  camera_depth:
    data_type: PointCloud2
    topic: /zed2/zed_node/point_cloud/ds_no_plane_cloud_registered
    update_frequency: 10
    publish_frequency: 5
    marking: true
    clearing: true
    min_obstacle_height: 0.05
    max_obstacle_height: 0.2
    track_unknown_space: true
    obstacle_range: 1.5
    raytrace_range: 2
    observation_persistence: 0.0
    # decay_time: 1.0
    
inflation_layer:
  enabled:              true
  #cost_scaling_factor:  2.0 # exponential rate at which the obstacle cost drops off (default: 10)
  cost_scaling_factor:  1 # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.05 # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true
  map_topic:            "/map"

virtualWall_layer:
  enabled:              true
  topic:  "/virtualWall_cloudPoint"
  map_topic:            "/map"

# sonar_layer:
#   enabled:            true
#   clear_threshold:    0.2
#   mark_threshold:     0.8
#   topics: ["/sonar0", "/sonar1", "/sonar2", "/sonar3", "/sonar4"]
#   clear_on_max_reading: true
