global_costmap:
   global_frame: map  # The name of the global frame used for the global costmap.
   robot_base_frame: base_footprint  # The name of the robot base frame used in the costmap.
   update_frequency: 20  # The frequency (in Hz) at which the global costmap is updated.
   publish_frequency: 5  # The frequency (in Hz) at which the global costmap is published.
   static_map: true  # Flag indicating whether the global costmap uses a static map as a base.
   rolling_window: false  # Flag indicating whether to use a rolling window approach for the global costmap.
   resolution: 0.05  # The resolution (in meters per cell) of the global costmap.
   transform_tolerance: 1.0  # The tolerance (in seconds) for waiting on transform data.
   map_type: costmap  # The type of the global costmap.

   plugins:
   - {name: static_layer,        type: "costmap_2d::StaticLayer"}  # Plugin configuration for the static layer.
   - {name: obstacle_layer,      type: "costmap_2d::VoxelLayer"}  # Plugin configuration for the obstacle layer.
   # - {name: virtualWall_layer,   type: "costmap_2d::VirtualWallLayer"}  # Plugin configuration for the virtual wall layer.
   - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}  # Plugin configuration for the inflation layer.

GlobalPlanner:        
   allow_unknown: false  # Flag indicating whether the global planner allows for unknown areas in the map.
