#For full documentation of the parameters in this file, and a list of all the
#parameters available for DWAPlannerROS, please see
#http://www.ros.org/wiki/dwa_local_planner
EBandPlannerROS:

  differential_drive: False #%holonomic_robot: true

  xy_goal_tolerance: 0.05 # m
  yaw_goal_tolerance: 0.2 # rad
  rot_stopped_vel: 0.01
  trans_stopped_vel: 0.01

  marker_lifetime: 0.5
  
  #===  Elastic Band Parameters  ===
  eband_min_relative_overlap: 0.5
  eband_tiny_bubble_distance: 0.1
  eband_tiny_bubble_expansion: 0.1
  eband_internal_force_gain: 1.0
  eband_external_force_gain: 2.0
  num_iterations_eband_optimization: 3
  eband_equilibrium_approx_max_recursion_depth: 4
  eband_equilibrium_relative_overshoot: 0.75
  eband_significant_force_lower_boundt: 0.15
  costmap_weight: 20.0

  
  #===  Trajectory Controller Parameters  ===

  max_vel_lin: 0.21
  max_vel_th: 0.18
  min_vel_lin: 0.9
  min_vel_th: 0.9
  min_in_place_vel_th: 0.0
  in_place_trans_vel: 0.0
  k_prop: 4.0    # angular velocity pid
  k_damp: 3.5
  
  Ctrl_Rate: 10.0
  max_acceleration: 1.0
  virtual_mass: 0.75
  max_translational_acceleration : 1.0
  max_rotational_acceleration : 0.4
  rotation_correction_threshold : 0.5

  bubble_velocity_multiplier : 5.0
  rotation_threshold_multiplier : 0.3
  disallow_hysteresis : False
