planner_configs:
  SBLkConfigDefault:
    type: geometric::SBL
  ESTkConfigDefault:
    type: geometric::EST
  LBKPIECEkConfigDefault:
    type: geometric::LBKPIECE
  BKPIECEkConfigDefault:
    type: geometric::BKPIECE
  KPIECEkConfigDefault:
    type: geometric::KPIECE
  RRTkConfigDefault:
    type: geometric::RRT
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
  RRTstarkConfigDefault:
    type: geometric::RRTstar
  TRRTkConfigDefault:
    type: geometric::TRRT
  PRMkConfigDefault:
    type: geometric::PRM
  PRMstarkConfigDefault:
    type: geometric::PRMstar
arm_torso:
  planner_configs:
    - SBLkConfigDefault
    - ESTkConfigDefault
    - LBKPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - KPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - RRTstarkConfigDefault
    - TRRTkConfigDefault
    - PRMkConfigDefault
    - PRMstarkConfigDefault
  projection_evaluator: joints(torso_lift_joint,arm_1_joint)
  longest_valid_segment_fraction: 0.01
arm:
  planner_configs:
    - SBLkConfigDefault
    - ESTkConfigDefault
    - LBKPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - KPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - RRTstarkConfigDefault
    - TRRTkConfigDefault
    - PRMkConfigDefault
    - PRMstarkConfigDefault
  projection_evaluator: joints(arm_1_joint, arm_2_joint)
  longest_valid_segment_fraction: 0.01
base:
  planner_configs:
    - AnytimePathShortening
    - SBL
    - EST
    - LBKPIECE
    - BKPIECE
    - KPIECE
    - RRT
    - RRTConnect
    - RRTstar
    - TRRT
    - PRM
    - PRMstar
    - FMT
    - BFMT
    - PDST
    - STRIDE
    - BiTRRT
    - LBTRRT
    - BiEST
    - ProjEST
    - LazyPRM
    - LazyPRMstar
    - SPARS
    - SPARStwo
  projection_evaluator: joints(odom_y,odom_x)
  longest_valid_segment_fraction: 0.005
whole_body:
  planner_configs:
    - AnytimePathShortening
    - SBL
    - EST
    - LBKPIECE
    - BKPIECE
    - KPIECE
    - RRT
    - RRTConnect
    - RRTstar
    - TRRT
    - PRM
    - PRMstar
    - FMT
    - BFMT
    - PDST
    - STRIDE
    - BiTRRT
    - LBTRRT
    - BiEST
    - ProjEST
    - LazyPRM
    - LazyPRMstar
    - SPARS
    - SPARStwo
  projection_evaluator: joints(odom_y,odom_x)
  longest_valid_segment_fraction: 0.005
